"""empty message

Revision ID: 49a23e7fa441
Revises: b62d3c164e8b
Create Date: 2025-04-18 07:12:42.383334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a23e7fa441'
down_revision: Union[str, None] = 'b62d3c164e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_and_answer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem_and_answer', 'users', ['user_id'], ['id'])
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    op.drop_constraint(None, 'problem_and_answer', type_='foreignkey')
    op.drop_column('problem_and_answer', 'user_id')
    # ### end Alembic commands ###
