"""empty message

Revision ID: b62d3c164e8b
Revises: e37a759a16bc
Create Date: 2025-04-18 06:13:13.754115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62d3c164e8b'
down_revision: Union[str, None] = 'e37a759a16bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_types', sa.Column('icon', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection_types', 'icon')
    # ### end Alembic commands ###
