"""empty message

Revision ID: e37a759a16bc
Revises: eb33b838d793
Create Date: 2025-04-18 06:06:44.298703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37a759a16bc'
down_revision: Union[str, None] = 'eb33b838d793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skills', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'user_id')
    # ### end Alembic commands ###
